#!/bin/sh /etc/rc.common
#Author:corecode
#Modifier:superlc

START=55
STOP=10

start()
{

if [ $(uci get easydrcom.@login[0].boot) ] ;
then
	/etc/init.d/easydrcomd enable
else
	/etc/init.d/easydrcomd disable
fi

if [ $(uci get easydrcom.@login[0].enable) ] ;
then
	echo [General] > /etc/config/easydrcom.conf
	echo UserName=$(uci get easydrcom.@login[0].UserName) >> /etc/config/easydrcom.conf
	echo PassWord=$(uci get easydrcom.@login[0].PassWord) >> /etc/config/easydrcom.conf
	echo Mode=$(uci get easydrcom.@login[0].Mode) >> /etc/config/easydrcom.conf
	echo AutoOnline=1 >> /etc/config/easydrcom.conf
	echo AutoRedial=$(uci get easydrcom.@login[0].AutoRedial) >> /etc/config/easydrcom.conf
	echo [Remote] >> /etc/config/easydrcom.conf
	echo IP=$(uci get easydrcom.@login[0].IP) >> /etc/config/easydrcom.conf
	echo Port=$(uci get easydrcom.@login[0].Port) >> /etc/config/easydrcom.conf
	echo UseBroadcast=$(uci get easydrcom.@login[0].UseBroadcast) >> /etc/config/easydrcom.conf
	echo MAC=$(uci get easydrcom.@login[0].MAC) >> /etc/config/easydrcom.conf
	echo [Local] >> /etc/config/easydrcom.conf
	echo NIC=$(uci get easydrcom.@login[0].NIC) >> /etc/config/easydrcom.conf
	echo EAPTimeout=$(uci get easydrcom.@login[0].EAPTimeout) >> /etc/config/easydrcom.conf
	echo UDPTimeout=$(uci get easydrcom.@login[0].UDPTimeout) >> /etc/config/easydrcom.conf
  echo HostName=$(uci get easydrcom.@login[0].HostName) >> /etc/config/easydrcom.conf
  echo KernelVersion=$(uci get easydrcom.@login[0].KernelVersion) >> /etc/config/easydrcom.conf
	easydrcom  -r -b -c /etc/config/easydrcom.conf &
	echo "EasyDrcom Client has started."
else
	stop
fi


}

stop()
{
	killall easydrcom
	echo "EasyDrcom Client has stoped."
}

restart()
{
stop
start
}
