#!/bin/sh /etc/rc.common
# easydrcom script

START=96

start(){
	easydrcom -b -r -c /etc/config/easydrcom.conf &
	echo "easydrcom started"
}

stop(){
	killall easydrcom
	echo "easydrcom stopped"
}

restart(){
	stop
	start
}
